### ISSUE TITLE
add Javascript solutions for project euler problems

### ISSUE THREAD

**Issue by imabhishekkumar** [RisingLight/Project-Euler#18]

**Comment by MatheusMuriel** [comment]
I'll work on it :D 
https://github.com/MatheusMuriel/Project-Euler

**Comment by MatheusMuriel** [comment]
My PR for problem 2: https://github.com/RisingLight/Project-Euler/pull/21

**Comment by MatheusMuriel** [comment]
I reorganized the javascript solutions and created a new PR

https://github.com/RisingLight/Project-Euler/pull/68
