### ISSUE TITLE
add C++ solutions for project euler problems

### ISSUE THREAD

**Issue by imabhishekkumar** [RisingLight/Project-Euler#24]

**Comment by BuzzHari** [comment]
Would you accept solutions in C?

**Comment by imabhishekkumar** [comment]
@BuzzHari, we have created a directory for C as well.

**Comment by Kuljeet-123** [comment]
@imabhishekkumar  I want to add some solutions.

**Comment by Kuljeet-123** [comment]
@imabhishekkumar please review my PR and merge into your repo and this is for prblem 04 and  my PR id is #65 .
